total_steps_gail: 500000
total_steps_sqil: 100000
dqfd_pretrain_steps: 20000
discrete: True
max_steps_per_traj: 1000

dqn: { learning_starts: 10000 }

cluster_config:
  {
    cluster_type_gail: "agglomerative",
    cluster_type_sqil: "kmeans",
    agglomerative_clustering_kwargs:
      { metric: "l2", linkage: "average", distance_threshold: 0.1 },
    kmeans_clustering_kwargs:
      { n_clusters: 100, max_iter: 300, algorithm: "lloyd" },
  }

prune_config:
  {
    prune_type: "value",
    group_filtering_kwargs:
      { size_threshold: 100, measure_cutoff: 50, method: "variance" },
    action_filtering_kwargs:
      { size_threshold: 100, measure_cutoff: 50, method: "variance", percentile: 50 },
    outcome_filtering_kwargs:
      { horizon: 10, metric: "variance", cutoff: 75 },
    value_filtering_kwargs:
      { cutoff: 50 }
  }
